version: '2'
services:
  todo:
#    build:
#      context: ./app
    image: msandro1610/todo-list
    container_name: todo-list
    restart: unless-stopped
    env_file: .env
    environment:
      TZ: Asia/Jakarta
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: todo
      MYSQL_PASSWORD: Todo2023
      MYSQL_DBNAME: todo_list
#    volumes:
#      - ./:/app
    ports:
      - 0.0.0.0:3030:3030
    depends_on:
      - db

  db:
    image: mysql
    container_name: todo-db
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
#    ports:
#      - 0.0.0.0:33062:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Todo2023!
      MYSQL_DATABASE: todo_list
      MYSQL_USER: todo
      MYSQL_PASSWORD: Todo2023
